project_id = "ghjueojobnchdiavypku"

[functions.verify-admin-pin]
verify_jwt = false

[functions.rotate-admin-pin]
verify_jwt = false

[functions.init-admin-pin]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.sign-document]
verify_jwt = false

[functions.verify-document]
verify_jwt = false